/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRecoveryRouteImport } from './routes/admin-recovery'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRosterRouteImport } from './routes/_authenticated/roster'
import { Route as AuthenticatedRolesRouteImport } from './routes/_authenticated/roles'
import { Route as AuthenticatedMembersRouteImport } from './routes/_authenticated/members'
import { Route as AuthenticatedDependantsRouteImport } from './routes/_authenticated/dependants'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedEventsIndexRouteImport } from './routes/_authenticated/events/index'
import { Route as ApiPublicAdminRecoveryRouteImport } from './routes/api/public/admin-recovery'
import { Route as AuthenticatedReceiptsContributionIdRouteImport } from './routes/_authenticated/receipts/$contributionId'
import { Route as AuthenticatedEventsIdRouteImport } from './routes/_authenticated/events/$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRecoveryRoute = AdminRecoveryRouteImport.update({
  id: '/admin-recovery',
  path: '/admin-recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRosterRoute = AuthenticatedRosterRouteImport.update({
  id: '/roster',
  path: '/roster',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRolesRoute = AuthenticatedRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMembersRoute = AuthenticatedMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDependantsRoute = AuthenticatedDependantsRouteImport.update({
  id: '/dependants',
  path: '/dependants',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEventsIndexRoute =
  AuthenticatedEventsIndexRouteImport.update({
    id: '/events/',
    path: '/events/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicAdminRecoveryRoute = ApiPublicAdminRecoveryRouteImport.update({
  id: '/api/public/admin-recovery',
  path: '/api/public/admin-recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedReceiptsContributionIdRoute =
  AuthenticatedReceiptsContributionIdRouteImport.update({
    id: '/receipts/$contributionId',
    path: '/receipts/$contributionId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEventsIdRoute = AuthenticatedEventsIdRouteImport.update({
  id: '/events/$id',
  path: '/events/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-recovery': typeof AdminRecoveryRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dependants': typeof AuthenticatedDependantsRoute
  '/members': typeof AuthenticatedMembersRoute
  '/roles': typeof AuthenticatedRolesRoute
  '/roster': typeof AuthenticatedRosterRoute
  '/events/$id': typeof AuthenticatedEventsIdRoute
  '/receipts/$contributionId': typeof AuthenticatedReceiptsContributionIdRoute
  '/api/public/admin-recovery': typeof ApiPublicAdminRecoveryRoute
  '/events/': typeof AuthenticatedEventsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-recovery': typeof AdminRecoveryRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dependants': typeof AuthenticatedDependantsRoute
  '/members': typeof AuthenticatedMembersRoute
  '/roles': typeof AuthenticatedRolesRoute
  '/roster': typeof AuthenticatedRosterRoute
  '/events/$id': typeof AuthenticatedEventsIdRoute
  '/receipts/$contributionId': typeof AuthenticatedReceiptsContributionIdRoute
  '/api/public/admin-recovery': typeof ApiPublicAdminRecoveryRoute
  '/events': typeof AuthenticatedEventsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/admin-recovery': typeof AdminRecoveryRoute
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/dependants': typeof AuthenticatedDependantsRoute
  '/_authenticated/members': typeof AuthenticatedMembersRoute
  '/_authenticated/roles': typeof AuthenticatedRolesRoute
  '/_authenticated/roster': typeof AuthenticatedRosterRoute
  '/_authenticated/events/$id': typeof AuthenticatedEventsIdRoute
  '/_authenticated/receipts/$contributionId': typeof AuthenticatedReceiptsContributionIdRoute
  '/api/public/admin-recovery': typeof ApiPublicAdminRecoveryRoute
  '/_authenticated/events/': typeof AuthenticatedEventsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-recovery'
    | '/login'
    | '/dashboard'
    | '/dependants'
    | '/members'
    | '/roles'
    | '/roster'
    | '/events/$id'
    | '/receipts/$contributionId'
    | '/api/public/admin-recovery'
    | '/events/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-recovery'
    | '/login'
    | '/dashboard'
    | '/dependants'
    | '/members'
    | '/roles'
    | '/roster'
    | '/events/$id'
    | '/receipts/$contributionId'
    | '/api/public/admin-recovery'
    | '/events'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin-recovery'
    | '/login'
    | '/_authenticated/dashboard'
    | '/_authenticated/dependants'
    | '/_authenticated/members'
    | '/_authenticated/roles'
    | '/_authenticated/roster'
    | '/_authenticated/events/$id'
    | '/_authenticated/receipts/$contributionId'
    | '/api/public/admin-recovery'
    | '/_authenticated/events/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AdminRecoveryRoute: typeof AdminRecoveryRoute
  LoginRoute: typeof LoginRoute
  ApiPublicAdminRecoveryRoute: typeof ApiPublicAdminRecoveryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-recovery': {
      id: '/admin-recovery'
      path: '/admin-recovery'
      fullPath: '/admin-recovery'
      preLoaderRoute: typeof AdminRecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/roster': {
      id: '/_authenticated/roster'
      path: '/roster'
      fullPath: '/roster'
      preLoaderRoute: typeof AuthenticatedRosterRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/roles': {
      id: '/_authenticated/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AuthenticatedRolesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/members': {
      id: '/_authenticated/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AuthenticatedMembersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dependants': {
      id: '/_authenticated/dependants'
      path: '/dependants'
      fullPath: '/dependants'
      preLoaderRoute: typeof AuthenticatedDependantsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/events/': {
      id: '/_authenticated/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof AuthenticatedEventsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/admin-recovery': {
      id: '/api/public/admin-recovery'
      path: '/api/public/admin-recovery'
      fullPath: '/api/public/admin-recovery'
      preLoaderRoute: typeof ApiPublicAdminRecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/receipts/$contributionId': {
      id: '/_authenticated/receipts/$contributionId'
      path: '/receipts/$contributionId'
      fullPath: '/receipts/$contributionId'
      preLoaderRoute: typeof AuthenticatedReceiptsContributionIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/events/$id': {
      id: '/_authenticated/events/$id'
      path: '/events/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof AuthenticatedEventsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDependantsRoute: typeof AuthenticatedDependantsRoute
  AuthenticatedMembersRoute: typeof AuthenticatedMembersRoute
  AuthenticatedRolesRoute: typeof AuthenticatedRolesRoute
  AuthenticatedRosterRoute: typeof AuthenticatedRosterRoute
  AuthenticatedEventsIdRoute: typeof AuthenticatedEventsIdRoute
  AuthenticatedReceiptsContributionIdRoute: typeof AuthenticatedReceiptsContributionIdRoute
  AuthenticatedEventsIndexRoute: typeof AuthenticatedEventsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDependantsRoute: AuthenticatedDependantsRoute,
  AuthenticatedMembersRoute: AuthenticatedMembersRoute,
  AuthenticatedRolesRoute: AuthenticatedRolesRoute,
  AuthenticatedRosterRoute: AuthenticatedRosterRoute,
  AuthenticatedEventsIdRoute: AuthenticatedEventsIdRoute,
  AuthenticatedReceiptsContributionIdRoute:
    AuthenticatedReceiptsContributionIdRoute,
  AuthenticatedEventsIndexRoute: AuthenticatedEventsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AdminRecoveryRoute: AdminRecoveryRoute,
  LoginRoute: LoginRoute,
  ApiPublicAdminRecoveryRoute: ApiPublicAdminRecoveryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
